version: '3.8'

services:

  db:
    container_name: postgres_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zoo
    ports:
      - "54320:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - db:/docker-entrypoint-initdb.d/

volumes:
  pg_data:
  db:
